# Generated by Django 5.1.1 on 2024-09-20 04:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writtenletter',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
